title: UCSC Math
email: zsschwab@ucsc.edu
description: A site to host math content starting with Bob
baseurl: ""
url: "https://UCSCMath.github.io"

remote_theme: ZachariahSWS/Academia-Theme
theme_settings:
  navigation:
    - title: Home
      url: /
    - title: Math 23A
      url: /Bob/23a
    - title: Math 100
      url: /Bob/100
    - title: Math 105A
      url: /Bob/105a
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

author: Zachariah Schwab
