title: UCSC Math
email: zsschwab@ucsc.edu
description: A site to host math content starting with Bob
baseurl: ""
url: "https://UCSCMath.github.io"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: Zachariah Schwab
